#!/bin/bash

scriptname=$(basename $0)
pidfile="/tmp/${scriptname}"

# lock it
exec 200>$pidfile
flock -n 200 || exit 1
pid=$$
echo $pid 1>&200

echo "starting service-runner"

while :
do
    flag=$(redis-cli lpop service-runner)
    if [ $flag ]; then
        echo "flag: "$flag
        IFS=\> read script logfile <<< "$flag"
        echo "STARTING: $script > $logfile"
        $script > $logfile
        if [ ! -e $logfile ]; then
            touch $logfile
        fi
        echo "COMPLETE: $script > $logfile"
    fi

    sleep 0.1
done
